<?php

namespace App\Models\Forum\Entities;

use App\Models\Model;
use App\Models\Forum\Entities\User;
use App\Modules\Bbs\Database\factories\TopicFactory;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;

class Topic extends Model
{
    protected $primaryKey = 'topic_id';
    protected $is_delete = 0;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        $callback = function(){
            self::getAllTopics(-1,true);
        };

        self::updated($callback);

        self::saved($callback);

        self::deleted($callback);
    }

    protected static function newFactory()
    {
        return TopicFactory::new();
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'user_id');
    }

    public function isFollow()
    {
        return $this->hasOne(TopicFollow::class, $this->primaryKey, $this->primaryKey);
    }

    public static function clearTopicsCache()
    {
        Cache::tags('topics')->flush();
    }

    // 获取所有的话题列表
    public static function getAllTopics($limit = -1, bool $force = false)
    {
        $key = 'topics:limit:' . $limit;
        if ($force){
            Cache::tags('topics')->delete($key);
        }
        return Cache::tags('topics')->remember($key, Carbon::now()->addDays(7 + rand(0, 7)), function () use ($limit){
            $build = Topic::getInstance();
            if ($limit > 0) {
                $build = $build->limit($limit)->where('dynamic_count', '>', 0);
            }
            return $build->orderBy('topic_sort', 'ASC')->orderBy('follow_count', 'DESC')->get();
        });
    }

    public static function getListByIds(array $ids)
    {
        $list = self::whereIn('topic_id', $ids)->select('topic_id', 'topic_name')->get()->toArray();
        return array_column($list, null, 'topic_id');
    }

    /**
     * 获取默认的话题Id
     *
     * @return int
     */
    public static function getDetaultTopicId(): int
    {
        return (int)self::where('is_default', 1)->value('topic_id', 0);
    }
}
